### PR TITLE
More info page added, acoustic indices desc added, acoustic indice rounding added

### PR DESCRIPTION
**Pull request by JoshEKruse-zz**

### CODE REVIEW

**Review by BigNasty000 — APPROVED** [review]
The changes are great. Only comment would be the size of the graphs on the information page is slightly large, but that's not a priority right now!

**Comment by stevenenriquez** [comment]
Looks good. I added a couple commits for adjusting the padding and setting a width for the images so they're not too big and for including subcategories of biophony/geophony/anthrophony and the accuracies for each model. I just need to add those commits to this pull request

**Comment by stevenenriquez** [comment]
Looks good. I added a couple commits for adjusting the padding and setting a width for the images so they're not too big and for including subcategories of biophony/geophony/anthrophony and the accuracies for each model. I just need to add those commits to this pull request

**Comment by stevenenriquez** [comment]
Looks good. I added a couple commits for adjusting the padding and setting a width for the images so they're not too big and for including subcategories of biophony/geophony/anthrophony and the accuracies for each model. I just need to add those commits to this pull request

**Pull request merged**
